// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Hamburger': typeof import("../../components/hamburger.vue")['default'],
    'Headline': typeof import("../../components/headline.vue")['default'],
    'HorizontalList': typeof import("../../components/horizontal-list.vue")['default'],
    'Leftbar': typeof import("../../components/leftbar.vue")['default'],
    'Loading': typeof import("../../components/loading.vue")['default'],
    'Navbar': typeof import("../../components/navbar.vue")['default'],
    'PageTitle': typeof import("../../components/page-title.vue")['default'],
    'Popular': typeof import("../../components/popular.vue")['default'],
    'Posts': typeof import("../../components/posts.vue")['default'],
    'SinglePost': typeof import("../../components/single-post.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
  }
}
export {}
